language: node_js
node_js:
  - 12.19.0

before_install:
  - npm install -g npm@latest

install:
- npm install
- cd node_modules && cd scratch-l10n && npm install && npm run-script build && cd .. && cd ..

script:
# - echo "Success!"
 - npm run build
 - npm run deploy